In [3]:
import numpy as np
import cv2

In [14]:
np.random.randint(0,100,100).reshape(10,10)

array([[ 5, 24,  1, 47, 70, 32, 39, 90, 73,  6],
       [15, 36, 26,  9, 44, 83,  9, 83, 57, 93],
       [24, 42, 56,  9, 75, 14, 90, 34, 23, 58],
       [34, 82, 99, 39, 35, 24, 89, 74, 99, 30],
       [78, 25, 70, 37, 80, 98, 19, 90, 28, 32],
       [70, 99, 84, 78, 56, 37, 57, 29, 94, 22],
       [21, 61,  8, 39, 86, 77, 55, 54, 97, 15],
       [71,  6, 32, 48, 84, 57, 68, 81, 62, 31],
       [61, 64, 22,  5, 13, 79, 28, 39, 65,  2],
       [66, 77, 29,  4, 35,  8, 31, 23, 97, 19]])

In [24]:
c = np.arange(60).reshape(3,4,5)
c

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [17]:
c.sum(axis=1)

array([[ 30,  34,  38,  42,  46],
       [110, 114, 118, 122, 126],
       [190, 194, 198, 202, 206]])

In [4]:
image = cv2.imread('myphoto.jpg') # R G B

In [5]:
point = image[50,500]

In [10]:
point =[255,255,255]

In [11]:
image[100:150,500:550] = [255,255,255]

In [14]:
cv2.imshow('input_image', image)
cv2.waitKey(0)
cv2.destroyAllWindows()